# -*- coding: utf-8 -*-
"""Copy of ashik3519.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bfU32Z9XaKTGepgK8sbrPuwnwUH9mgRb
"""

import hashlib
import os

def hash_password(password):
    salt = os.urandom(32)
    hashed_password = hashlib.pbkdf2_hmac('sha256', password.encode('utf-8'), salt, 100000)
    return salt + hashed_password

def save_credentials(username, password, filename="credentials.txt"):
    hashed_password = hash_password(password)
    with open(filename, "a") as file:
        file.write(f"{username}:{hashed_password.hex()}\n")
    print("Credentials saved successfully!")

def check_credentials(username, password, filename="credentials.txt"):
    try:
        with open(filename, "r") as file:
            for line in file:
                stored_username, stored_hashed_password = line.strip().split(":")
                stored_hashed_password = bytes.fromhex(stored_hashed_password)
                salt = stored_hashed_password[:32]
                stored_hash = stored_hashed_password[32:]
                input_hash = hashlib.pbkdf2_hmac('sha256', password.encode('utf-8'), salt, 100000)
                if username == stored_username and input_hash == stored_hash:
                    return True
    except FileNotFoundError:
        print("No credentials file found.")
    return False

def print_all_credentials(filename="credentials.txt"):
    try:
        with open(filename, "r") as file:
            for line in file:
                print(line.strip())
    except FileNotFoundError:
        print("No credentials file found.")

def main():
    while True:
        choice = input("Do you want to (1) Register or (2) Login? (3) Print all credentials (4) Exit: ")
        if choice == "1":
            username = input("Enter username: ")
            password = input("Enter password: ")
            save_credentials(username, password)
        elif choice == "2":
            username = input("Enter username: ")
            password = input("Enter password: ")
            if check_credentials(username, password):
                print("Login successful!")
            else:
                print("Invalid username or password.")
        elif choice == "3":
            print_all_credentials()
        elif choice == "4":
            break
        else:
            print("Invalid choice, please try again.")

if __name__ == "__main__":
    main()